development:
  adapter: postgresql
  database: consorcio_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: consorcio_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: consorcio
  pool: 5
  timeout: 5000
